sudo: required

language: python

python:
    - 3.5

services:
    - docker

before_script:
    - mkdir -p ~/cs4501/db
    - docker pull mysql:5.7.14
    - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
    - sleep 10
    - docker run --name mysql-cmdline -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' --link mysql:db mysql:5.7.14
    - docker exec -it mysql-cmdline bash -c "mysql -u root -p'\$3cureUS' -h db -e 'create database cs4501 character set utf8;'"
    - docker exec -it mysql-cmdline bash -c "mysql -u root -p'\$3cureUS' -h db -e 'create user \"www\"@\"%\" identified by \"\$3cureUS\";'"
    - docker exec -it mysql-cmdline bash -c "mysql -u root -p'\$3cureUS' -h db -e 'grant all on cs4501.* to \"www\"@\"%\";' "
    - docker exec -it mysql-cmdline bash -c "mysql -u root -p'\$3cureUS' -h db -e 'grant all on test_cs4501.* to \"www\"@\"%\";' "
    - docker-compose up

script:
    - docker ps -a

notifications:
  email: false
