models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - /app/grubbr:/app
    ports:
      - "8001:8000"
    command: bash -c "mod_wsgi-express start-server --working-directory /app --reload-on-changes app/grubbr/app/wsgi.py"
