models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./grubbr_models:/app
    ports:
      - "8001:8000"

    command: bash -c "python /app/manage.py makemigrations && python /app/manage.py migrate && python /app/manage.py loaddata /app/db.json && mod_wsgi-express start-server --working-directory /app/ --reload-on-changes /app/grubbr_models/wsgi.py"
    #removed tests because they were causing a problem

exp:
  image: tp33/django
  links:
     - models:models-api
  ports:
     - "8002:8000"
  volumes:
     - ./grubbr_exp:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/grubbr_exp/wsgi.py"

web:
  image: tp33/django
  links:
     - exp:exp-api
  ports:
     - "8000:8000"
  volumes:
     - ./grubbr_web:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/grubbr_web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka
   
es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
     - .:/app
   command: ["./wait-for-it.sh", "kafka:9092", "--", "python", "/app/kafka_script.py"]